project:
  type: website
  output-dir: docs

website:
  title: "Mario Arce Acosta"
  google-analytics: "G-SXS7GJZXP7"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Portfolio
      - href: freelance.qmd
        text: Freelancing
          
      - href: blog.qmd
        text: Blog    
          
      - text: "Other Work"       # The Header Name (e.g., 'Research', 'Portfolio')
        menu:
        - href: presentations.qmd
          text: Conferences & Presentations

        
      - href: files/_Academic__Mario_CV.pdf
        text: CV

format:
  html:
    theme: #litera, sandstone, superhero
      light: [litera, custom.scss]
      dark: [superhero, custom.scss]
    css: styles.css
    toc: true
filters:
  - lightbox
lightbox: auto

editor: visual

